project:
  type: website
  output-dir: docs
  
website:
  title: "Lauren George BIOL 806 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/la-george/laurengeorge.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Lauren George"

format:
  html:
    theme: quartz
    toc: true

editor: source

